<?php

namespace AppBundle\Repository;

/**
 * footballTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class footballTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
